exclude:
- tmp/**/*
- vendor/bundle/**/*
linters:
  InlineStyles:
    enabled: false
  InstanceVariables:
    enabled: false
  LineLength:
    enabled: false
  RuboCop:
    ignored_cops:
    - Style/IfUnlessModifier
  ViewLength:
    enabled: false
