default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: feusport
  username: feusport
  password: feusport

development:
  <<: *default

test:
  <<: *default
  database: feusport-test
  host: <%= ENV['POSTGRES_HOST'].presence || 'localhost' %>

online_default: &online_default
  <<: *default
  database: <%= ENV['RAILS_DB_DATABASE'] %>
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

production:
  <<: *online_default

staging:
  <<: *online_default

preview:
  <<: *online_default