production:
  import_suggestions:
    class: ImportSuggestionsJob
    priority: 50
    schedule: 21 5 * * *
    class: Competitions::Publishing::ReminderJob
    priority: 40
    schedule: 0 10 * * tue
