production:
  competition_publishing_reminder_job:
    class: 'Competitions::Publishing::ReminderJob'
    priority: 40
    schedule: 0 10 * * tue
  import_suggestions:
    class: ImportSuggestionsJob
    priority: 50
    schedule: 21 5 * * *
  solid_queue_debug:
    class: DebugJob
    priority: 10
    schedule: '*/20 * * * *'
