# Be sure to restart your server when you modify this file.

# Shared secrets are available across all environments.

shared:
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4362a24a8d396549a043755b7f9eb7431e5428f3a71c0f21f8dec0ff98487b0c3c44a9c69fc68125ba28997ce58796d317ec16891e26d8ee7ccfeacf78e9a782
  encryption_key_derivation_salt: Oe0dCt3pLslia4nLkADHWmskBTfSRwb6
  encryption_primary_key: S0KXvOn2ar5TOKTBv7KBxqwguYgaIdUO

test:
  secret_key_base: 833d7fd77f7ede1c698ef08878133727aca295e1692348ab0674753c8232f82de3e81b099f46682e7b868487972ab1ffe99c333d7e9035ca2f5accfdf69c2f8a
  encryption_key_derivation_salt: Oe0dCt3pLslia4nLkADHWmskBTfSRwb6
  encryption_primary_key: S0KXvOn2ar5TOKTBv7KBxqwguYgaIdUO

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encryption_key_derivation_salt: <%= ENV["ENCRYPTION_KEY_DERIVATION_SALT"] %>
  encryption_primary_key: <%= ENV["ENCRYPTION_PRIMARY_KEY"] %>
