# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: feusport-test
          POSTGRES_USER: feusport
          POSTGRES_PASSWORD: feusport
    env:
      RAILS_ENV: test
      BUNDLE_WITHOUT: production development
      DATABASE_URL: "postgres://feusport:feusport@localhost:5432/feusport-test"
      SPEC_VIEWS_DEBUG_OUTPUT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.6'
          bundler-cache: true
      
      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Generate assets
        run: bin/rails assets:precompile

      - name: Run tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: production development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.6'
          bundler-cache: true
      
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
      - name: Lint HAML files
        run: bundle exec haml-lint --parallel
